# Generated by Django 5.1.3 on 2025-01-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_pelapor", models.CharField(max_length=100)),
                ("jenis_bencana", models.CharField(max_length=100)),
                ("lokasi_kejadian", models.CharField(max_length=200)),
                ("tanggal_kejadian", models.DateTimeField()),
                ("deskripsi", models.TextField()),
                ("foto", models.ImageField(upload_to="laporan/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
